### ISSUE TITLE
Applied "latest" and now unable to use Editor

### ISSUE THREAD

**Issue by Twilight-Computer** [givanz/Vvveb#130] opened 2024-06-11 11:02 UTC
I have been away for a while and whilst my website "mostly" works there are a few bugs about.

I opted to download and install "latest.zip" and retained the config and public/themes to rule out any old bugs. I also copied back my public/media folder for custom images.

The first issue was missing tables in the database (fixed by applying various SQL scripts). The most notable issue was the loss of all changes to the main index.html page and the fact that the editor will not run at all - just a rotating circle of dots.

I have rolled back to my backup version and the world is all good again - however, some guidance on how to methodically update my code or at least not break my home page would be appreciated. 

NOTE: nothing major shown in log files.

Keep up the good work - I think this project is AWESOME !

**Comment by givanz** [comment] 2024-06-11 23:32
> The first issue was missing tables in the database (fixed by applying various SQL scripts).

There are some recent changes to db schema mostly for ecommerce, the schema will be fixed after 1.0 release.

If some changes will be needed to schema after 1.0 release then they will be applied by the automatic update tool that will be enabled with 1.0.

> loss of all changes to the main index.html page

Layout changes made in the page builder are saved directly to theme files, this complicates the theme update process.

Theme update will work by diff patching to keep custom changes.

> the editor will not run at all - just a rotating circle of dots.

This might be caused by javascript files caching, it often happens after update, you can try clearing browser cache.

> some guidance on how to methodically update my code or at least not break my home page

You should skip updating public/themes directly or manually update only folders like cart checkout etc where changes were not made.

Most recent changes to landing theme are done in the checkout area.

If you want to integrate some changes made on a page you have customized, you can use something like https://meldmerge.org until automatic theme update will be available.
 
Thank you!

**Comment by Twilight-Computer** [comment] 2024-06-12 01:10
Interestingly, a copy in my Test area is working correctly ? 
I have been playing catch up and note some additional changes in the last 2 hours that I will apply to my Test environement.
2 questions - it appears the </> Code Editor is now removed / disabled in the Admin module ( or I need to enable it ? )
![image](https://github.com/givanz/Vvveb/assets/162770195/e0c9194f-06e8-48e5-b355-a79cc9dd8aa2)
and there seems to be a new DEBUG element at the bottom, but I cannot disable this by editing the env.php file (for Production) ?
![image](https://github.com/givanz/Vvveb/assets/162770195/f5bad5c3-3c84-4cf7-b4e3-3b924b532024)

**Comment by givanz** [comment] 2024-06-12 11:29
`latest.zip` has all the latest code changes before they are pushed to github and it's updated often.

The debug panel is from the debug plugin, you can disable it if you don't want to show the bottom debug panel.

The code editor is always enabled, there is no option to disable it.

Probably it is hidden behind the debug panel that displays at the bottom.

**Closed** 2024-09-30 09:16 UTC
